version: '2.4'
services:

  acme-ca-server:
    build: 
      context: .
      dockerfile: Dockerfile
    # image: acmeca-server:dev
    restart: always
    environment:
      EXTERNAL_URL: http://localhost:8080
      CA_ENCRYPTION_KEY: 9OHwDWcFuvjiI2nwP-sOAaxIJOxik-STZW0GKHGZ8VY=
      DB_DSN: postgresql://postgres:secret@db/postgres
    ports:
      - "8080:8080"
    networks:
      - net
    volumes:
      - ./ca.key:/import/ca.key:ro # needed once to import new ca
      - ./ca.pem:/import/ca.pem:ro # needed once to import new ca
    mem_limit: 250m

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - net
    volumes:
      - ./db:/var/lib/postgresql/data
    mem_limit: 250m

networks:
  net: