name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Add version file
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > version.json'

      - name: Create tar
        run: tar -czf nl-uzi-acme-ca-server_${{ env.RELEASE_VERSION }}.tar.gz app ./version.json

      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: nl-uzi-acme-ca-server_${{ env.RELEASE_VERSION }}
          path: nl-uzi-acme-ca-server_${{ env.RELEASE_VERSION }}.tar.gz